version: '3'

services:

  redis:
    restart: always
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]

  testproj:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bill_test_proj
    env_file:
      - ./environments
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  media:
